# Generated by Django 4.2.9 on 2024-03-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_comment_image_alter_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='title',
            field=models.TextField(max_length=50, verbose_name='Başlık'),
        ),
    ]
