# Generated by Django 4.2.9 on 2024-03-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='content',
            field=models.CharField(max_length=200, null=True, verbose_name='İçerik'),
        ),
    ]
