# Generated by Django 4.2.9 on 2024-03-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_category_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, editable=False, null=True)),
                ('content', models.CharField(max_length=200, null=True, verbose_name='İçerik')),
            ],
        ),
    ]
