# Generated by Django 4.2.9 on 2024-03-25 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_subcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Alt Kategori', 'verbose_name_plural': 'Alt Kategoriler'},
        ),
    ]
