# Generated by Django 4.2.9 on 2024-03-25 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_alter_subcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='altKategori',
            field=models.ManyToManyField(to='forum.subcategory', verbose_name='Alt Kategori'),
        ),
        migrations.AddField(
            model_name='comment',
            name='kategori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.category'),
        ),
    ]
