# Generated by Django 4.2.9 on 2024-03-25 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_comment_altkategori_comment_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='altkategori',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.category'),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='altKategori',
        ),
        migrations.AlterField(
            model_name='comment',
            name='kategori',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.category'),
        ),
        migrations.AddField(
            model_name='comment',
            name='altKategori',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.subcategory', verbose_name='Alt Kategori'),
        ),
    ]
