# Generated by Django 4.2.9 on 2024-03-25 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_subcategory_altkategori_remove_comment_altkategori_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='altkategori',
            new_name='kategori',
        ),
    ]
