# Generated by Django 4.2.9 on 2024-03-26 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_rename_altkategori_subcategory_kategori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='kategori',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtopic', to='forum.category'),
        ),
    ]
