# Generated by Django 4.2.9 on 2024-04-16 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0015_alter_subcategory_kategori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='kategori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.category'),
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(editable=False)),
                ('altKategori', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.subcategory')),
            ],
        ),
    ]
