# Generated by Django 4.2.9 on 2024-04-16 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0016_alter_subcategory_kategori_subjects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategori', 'verbose_name_plural': '01-Kategoriler'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Yorum', 'verbose_name_plural': '04-Yorumlar'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Alt Kategori', 'verbose_name_plural': '02-Alt Kategoriler'},
        ),
        migrations.AlterModelOptions(
            name='subjects',
            options={'verbose_name': 'Konu', 'verbose_name_plural': '03-Konu Başlıkları'},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='altKategori',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='kategori',
        ),
        migrations.AddField(
            model_name='comment',
            name='subjects',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.subjects'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='altKategori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.subcategory'),
        ),
    ]
