# Generated by Django 4.2.9 on 2024-04-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0018_category_created_at_subcategory_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
    ]
