# Generated by Django 4.2.9 on 2024-04-16 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0019_alter_subjects_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='content',
        ),
    ]
