# Generated by Django 4.2.9 on 2024-04-18 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0022_alter_category_options_alter_subcategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Alt Kategori', 'verbose_name_plural': '02-Alt Kategoriler'},
        ),
    ]
