# Generated by Django 4.2.9 on 2024-04-18 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0023_alter_subcategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Yorum', 'verbose_name_plural': '04-Yorumlar'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['name'], 'verbose_name': 'Alt Kategori', 'verbose_name_plural': '02-Alt Kategoriler'},
        ),
        migrations.AlterModelOptions(
            name='subjects',
            options={'ordering': ['name'], 'verbose_name': 'Konu', 'verbose_name_plural': '03-Konu Başlıkları'},
        ),
    ]
