# Generated by Django 4.2.9 on 2024-04-30 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0026_alter_category_name_alter_subcategory_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='subjects',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.subjects', verbose_name='Konu'),
        ),
    ]
